### ISSUE TITLE
请问这个上下分屏的软件是什么软件

### ISSUE THREAD

**Issue by MalikWilliams1greher** [i-abc/GB5#12]
https://github.com/i-abc/GB5/raw/main/images/1.gif

**Comment by MalikWilliams1greher** [comment]
怎么达到截图上的效果的 一边跑脚本 一边监控的   请问

**Comment by i-abc** [comment]
通用方法：Tmux 实现多窗格，htop 实现监控功能。
如果 SSH 客户端自带多窗格功能，则可替代 Tmux。比如我用的是 Termius，就没用 Tmux。

可参考：
- [基于 Tmux 的多会话终端管理示例](https://linux.cn/article-13107-1.html)
- [How can I enable Split View - Termius](https://support.termius.com/hc/en-us/articles/8003720178457-How-can-I-enable-Split-View-)
- [Linux htop 详解](https://zhuanlan.zhihu.com/p/296803907)
